### ISSUE TITLE
부탄여행기

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/projekt-jetzt#1]
### goal
- 부탄 여행 중 기록한 것을 온라인으로 옮긴다

### principle
- 컨텐츠 확장에 욕심부리지 않고 철저히 온라인화 하는 것에만 집중한다
단 스케치는 추가해도 좋다
- 내용을 일자별로만 정리한다. 이후 출판물로 만들 시 챕터 구성에 대해 생각한다
- 출판은 온라인 여행기가 완성되면 고려한다. 출판에 필요한 추가 작업을 하지 않도록 하자

### tasks
- [x] 사진들 편집
- [x] 사진 구글닥스로 옮기기
- [x] 사진들 시간-장소별로 정리
- [ ] text 옮기기
- [ ] cargo에서 아래 조건을 만족하는 적당한 template 찾기
  - latest가 아니라 old 순서대로 볼 수 있는가?
  - 카테고리를 만들 수 있는가?
  - 가로세로 사진을 섞어 사용하기 용이한가?
  - 컨텐츠를 한꺼번에 업로드 해도 낱장으로 보여줄 수 있는가?
  - 모바일 대응이 되는가?
- [ ] 텍스트와 사진들 옮겨넣기
- [ ] site label 디자인
- [ ] domain 선택
