### ISSUE TITLE
웹 포트폴리오 만들기

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/projekt-jetzt#3]
### goal
- 읽기 쉬운 포트폴리오 사이트를 만든다
- 어느 기기에서든 빠르게 로딩하여 볼 수 있도록 한다

### requirement
- 모바일 대응 (브라우저 os가 모바일이면 모바일용 layout으로 자동 전환)
- 태그에 따라 필터링
- xml로 data 넣을 수 있어야 함
- 한영전환

### principle
- 화려하게 만드려고 노력하지 않는다
- 내용 구성에 집중한다
- 디자인 대상물은 간단히, 문제정의와 해결방법, 결과적 반응에 집중한다 
- 과정은 기본적으로 생략하되 과정이 내세울만한 것이었다면 소개한다

##### 내용 포맷짜기
- [ ] 엑셀로 종류 분류
- [ ] 엑셀로 필요 comp 분류
- [ ] 포트폴리오에 올릴 내용들 취합하여 엑셀로 정리
- [ ] 대표 case 1개에 대해 bulletpoint 형식으로 쓸지, 줄글로 쓸지 테스트
- [ ] 정한 형식에 맞게 내용 text 작성
- [ ] 각 case에 대한 이미지 수집 및 가로세로 비율 조정
- [ ] 동영상 편집

##### 페이지 만들기
- [ ] 사용할 UI component 정의 (동영상, list이미지, single 이미지 등)
- [ ] 기본 layout 정의
- [ ] 대표 case 1개에 대한 ui component별 css style 짜기
- [ ] 자기소개 페이지 추가
- [ ] font 정의하기
- [ ] 나머지 case 추가
- [ ] 동영상 재생기능 추가
- [ ] 한영 전환기능 적용
- [ ] 태그 필터링 기능 적용
- [ ] 페이지 전환 transition 적용

##### publish
- [ ] 호스팅 서비스 증록 및 결제
- [ ] 포트폴리오 사이트 도메인 등록
- [ ] 파일 올리기
- [ ] 기기별 테스트
