### ISSUE TITLE
포탈 만들기

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/projekt-jetzt#4]
### goal
- 내 개성이 드러나는 블로그 숏컷모음 사이트를 만든다

### requirement
- responsive layout이 아닌, 브라우저 os 종류에 따라 다른 모바일 대응

### principle
- 기존 UI에 대한 원칙을 비틀어 재미있게 함으로써 신명수의 접근방식을 보여준다
  - 매 로딩 마다 랜덤으로 바뀌는 스타일
  - 매 로딩 마다 랜덤으로 바뀌는 배치
- 고유의 visual language를 표현한다
  - 굵은 선과 면의 사용
  - 전통 문양 사용

### tasks 
- [ ] 일러로 레이아웃 디자인
- [ ] 대표 frame 스타일 및 color 결정
- [ ] 요소별 아이콘 디자인 (대표 style case 1개에 대해서만)
- [ ] 요소 랜덤배치를 위한 box 크기 랜덤 test
- [ ] box 크기 랜덤하더라도 최소 갯수 확보되도록 구현
- [ ] 랜덤배치 시 간격 variation 있도록 구현
- [ ] 나머지 스타일 set color 결정
- [ ] hovering 인터랙션 구현
- [ ] facebook 프로필사진 api 연동
- [ ] insta latest image 업데이트 연동
### note

완성 이후 적용 고려 해볼 것

- 일정시간 이후 layout 바꾸는 것
- 완성 이후에 three.js 사용해서 3D로 돌아가게 만드는 것을 시작
