### ISSUE TITLE
지리산둘레길 블로그 포스팅

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/projekt-jetzt#5]
### goal
- 지리산 둘레길 트레킹 기록들을 온라인화

### tasks
- [ ] 일지들 모두 디지털로 옮기기
- [ ] 일지내용 보완
- [ ] 지도 이미지 생성
- [ ] 사진을 시기별로 분류
- [ ] 포스팅: 14S
- [ ] 포스팅: 14F
- [ ] 포스팅: 15F
- [ ] 포스팅: 16S
- [ ] 포스팅: 16F
- [ ] 포스팅: 17S
