### ISSUE TITLE
동영상 블로그 개편

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/projekt-jetzt#7]
# goal
2017년 12월 31일까지 촬영한, 일상의 풍경을 담은 10초 미만의 동영상들을 모두 온라인화 한다

# requirement
- youtube 또는 vimeo 영상의 컨트롤러를 숨기고 표시 가능

# task
- [x] 동영상 모두 취합
- [ ] cameo로 색조 보정
- [ ] 엑셀에 동영상들 날짜, 제목, comment 정리
- [ ] 블로그에 업로드
