### ISSUE TITLE
일상블로그들 개편

### ISSUE THREAD

**Issue by zommeworks** [zommeworks/projekt-jetzt#9]
### goal
- 유지보수가 편하고 포스팅을 대량으로 할 수 있는 블로그로 옮긴다

# requirement
- 낱장의 이미지를 대량으로 포스팅
- 카테고리 (또는 태그) 필터링
- 포스트 순서 조정 가능
- 개일 도메인 연동

# tasks
- [ ] cargo에서 위의 요구사항 만족하는 테마 찾기
- [ ] 여행사진들 한 폴더에 모아서 정리 (google drive async)
- [ ] 지금까지 포스팅한 사진들 다시 다 올리기

### related jobs
- [ ] #6 여행 블로그 (zommewhere)
- [ ] #7 동영상 블로그 (zommetimes)
